Use $consul::version instead of facter consul_version (Fix 09297fa)
Unless a host installed consul, facter `consul_version` returns undef and `versioncmp` raises evaluation error.

example:

> Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Undef (file: /etc/puppetlabs/code/environments/ci/vendor/modules/consul/manifests/service.pp, line: 51, column: 6) (file: /etc/puppetlabs/code/environments/ci/vendor/modules/consul/manifests/init.pp, line: 238)